# Generated by Django 5.1.6 on 2025-03-11 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.district')),
            ],
        ),
        migrations.CreateModel(
            name='Iyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iyer_name', models.CharField(max_length=100)),
                ('iyer_age', models.CharField(max_length=100)),
                ('iyer_mobile', models.CharField(max_length=100)),
                ('iyer_description', models.CharField(max_length=100)),
                ('iyer_instagram', models.URLField()),
                ('iyer_facebook', models.URLField()),
                ('iyer_youtube', models.URLField()),
                ('iyer_threads', models.URLField()),
                ('iyer_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
        ),
        migrations.CreateModel(
            name='MarriageHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_hall_name', models.CharField(max_length=100)),
                ('marriage_hall_contact', models.CharField(max_length=100)),
                ('marriage_hall_description', models.TextField()),
                ('marriage_hall_instagram', models.URLField()),
                ('marriage_hall_facebook', models.URLField()),
                ('marriage_hall_youtube', models.URLField()),
                ('marriage_hall_threads', models.URLField()),
                ('marriage_hall_location', models.URLField()),
                ('marriage_hall_slug', models.SlugField()),
                ('marriage_hall_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
        ),
    ]
