# Generated by Django 5.1.6 on 2025-03-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_marriagehall_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriagehall',
            name='marriage_hall_image',
            field=models.ImageField(default=1, upload_to='marriage_hall_images/'),
            preserve_default=False,
        ),
    ]
