# Generated by Django 5.1.6 on 2025-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_marriagehall_marriage_hall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriagehall',
            name='marriage_hall_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marriagehall',
            name='marriage_hall_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marriagehall',
            name='marriage_hall_location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marriagehall',
            name='marriage_hall_threads',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marriagehall',
            name='marriage_hall_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
