# Generated by Django 5.1.6 on 2025-03-16 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_marriagehall_marriage_hall_facebook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('business_image', models.ImageField(upload_to='businness_type_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='businness_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='marriagehall',
            name='marriage_hall_area',
        ),
        migrations.RemoveField(
            model_name='marriagehall',
            name='user',
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_description', models.TextField()),
                ('business_since', models.CharField(max_length=100)),
                ('business_contact', models.CharField(max_length=100)),
                ('business_whatsapp', models.CharField(max_length=100)),
                ('business_image_1', models.ImageField(upload_to='businness_images/')),
                ('business_image_2', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('business_image_3', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('business_image_4', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('business_image_5', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('business_instagram_link', models.URLField(blank=True, null=True)),
                ('business_facebook_link', models.URLField(blank=True, null=True)),
                ('business_youtube_link', models.URLField(blank=True, null=True)),
                ('business_x_link', models.URLField(blank=True, null=True)),
                ('business_location', models.URLField(blank=True, null=True)),
                ('business_slug', models.SlugField()),
                ('active', models.BooleanField(default=False)),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business_type')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='businness_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='businness_images/')),
                ('age', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('instagram_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('x_link', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service_type')),
            ],
        ),
        migrations.DeleteModel(
            name='Iyer',
        ),
        migrations.DeleteModel(
            name='MarriageHall',
        ),
    ]
